config/routes.rb
Snappyquiz2::Application.routes.draw do

  resources :questions

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' } do
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get "errors/file_not_found"
  get "errors/unprocessable"
  get "errors/internal_server_error"
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  get "quiz/ended_early"
  get "quiz/index"  
  post "quiz/start"
  get "quiz/question"
  post "quiz/question"
  post "quiz/answer"
  get "quiz/end"

  post "choices/create"
  post "choices/destroy"

  get "questions/index"

  root 'users#home'

end

app/views/layouts/_footer.html.erb
<div id="footer">
	<!-- <div class="row"> -->
		<div class="small-8 columns right" style="padding-right:3em;">
			<p class="copyright right">© 2013-2014 Jonathan Wexler</p>

		</div>
		<!-- <div class="small-8 small-8 pull-4 columns"> -->
		<!-- </div> -->
	<!-- </div> -->
</div>

app/views/layouts/_header.html.erb
<div id="header" class="bg-blue has-dropdown">
  <a class="sidebar-button show-for-small" id="sidebarButton" href="#sidebar">
    <%= image_tag("SnappyQuizLogo.png", :class=> "main_logo", size: "200x70", alt: "Menu wht") %> 
  </a>

  <div class="row hide-for-small">
    <div class="small-3 columns">
      <%= link_to(image_tag("SnappyQuizLogo.png", :class=> "main_logo" , size: "200x70", alt: "Menu wht"), root_path) %>
    </div>
    <div class="small-7 columns">
      <%= link_to("Play", quiz_index_path, :class => "button secondary nav_buttons")%>
      <%= link_to("Questions", questions_path, :class => "button secondary nav_buttons")%>
      <%= link_to("Connect", questions_path, :class => "button secondary nav_buttons")%>
      <br class="clear_both" />

    </div>
    <div class="small-2 columns">
      <div class="right">
        <% if user_signed_in? %>
        <div style="margin-top: 10px;">
        Signed in as <%= current_user.name %>. Not you?
        <%= link_to "Sign out", destroy_user_session_path%>
        </div>
        <% else %>
        <div id="signup">
          <%= link_to("", new_user_registration_path, class:"sign_up") %>
        </div>
          <%= link_to(image_tag("fb_sign_in.png", :style=> "margin-top:-15px;" , size: "200x70", alt: "Menu wht"), user_omniauth_authorize_path(:facebook)) %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_icons.html.erb
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
<link rel="apple-touch-icon" href="/apple-touch-icon.png" />
<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png" />
<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png" />
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png" />
<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png" />
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png" />
<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png" />
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png" />

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "SnappyQuiz" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "SnappyQuiz | by Jonathan Wexler" %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
  <%= render '/layouts/shim'%>
  <%= render '/layouts/icons'%>

</head>

<body>
  <div id="wrapper">

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= render '/layouts/header' %>

  <div class="row buffer_bottom">
    <div class="small-12 columns">
      <%= yield %>
    </div>
  </div>
  <%= javascript_include_tag "application" %>
</div>
  <%= render '/layouts/footer' %>

</body>
</html>

app/views/layouts/quiz.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "SnappyQuiz | by Jonathan Wexler" %></title>

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= csrf_meta_tags %>
  <%= render '/layouts/shim'%>
  <%= render '/layouts/icons'%>


</head>

<body onload="checkFirstVisit()">
<div id="wrapper">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= render '/layouts/header' %>
  <div class="row buffer_bottom">
    <div class="small-12 columns">
      <div class="small-8 small-offset-2 columns text-center">
        <%= yield %>
      </div>
    </div>
  </div>
  <%= javascript_include_tag "application" %>
</div>
  <%= render '/layouts/footer' %>
<!-- </div> -->
</body>
</html>